name: remix_ic
description: The most complete and updated Remix icon pack available on Flutter.
version: null
repository: https://github.com/rodrigopequeno/remix_icon

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ">=5.1.0 <10.0.0"

flutter:
  fonts:
    - family: Remix
      fonts:
        - asset: lib/fonts/remixicon.ttf
